name: Build and Compile

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH=$PATH:$(go env GOPATH)/bin


      - name: Generate gRPC code for Go
        run: |
          protoc --go_out=BackEnd/proto --go-grpc_out=BackEnd/proto BackEnd/proto/forum.proto
          protoc --go_out=BackEnd/proto --go-grpc_out=BackEnd/proto BackEnd/proto/chat.proto
          protoc --go_out=BackEnd/proto --go-grpc_out=BackEnd/proto BackEnd/proto/auth.proto

      - name: List generated files after protoc
        run: |
          ls -R BackEnd/proto

      - name: Check if forum.pb.go exists
        run: |
          if [ ! -f BackEnd/proto/user/forum.pb.go ]; then
            echo "forum.pb.go not found!"
            exit 1
          fi

      - name: Build BackEnd
        run: |
          cd BackEnd
          go mod tidy
          go clean -modcache  # 清理模块缓存

          go build ./...

      # - name: Generate gRPC code for FrontEnd
      #   run: |
      #     protoc -I ./BackEnd/proto ./BackEnd/proto/forum.proto --js_out=import_style=commonjs:./FrontEnd/src/proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./FrontEnd/src/proto
      #     protoc -I ./BackEnd/proto ./BackEnd/proto/chat.proto --js_out=import_style=commonjs:./FrontEnd/src/proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./FrontEnd/src/proto

      # - name: Build FrontEnd
      #   run: |
      #     cd FrontEnd
      #     npm install
      #     npm run build
